### ISSUE TITLE
Dark mode Anomalous behaviour when going into single recipe pages

### ISSUE THREAD

**Issue by Torfab** [alfg/opendrinks#811] opened 2020-10-04 21:03 UTC
I just noticed that light theme flash for an instant before going into dark mode on single recipe pages.

**Comment by KevinLu** [comment] 2020-10-11 02:30
Can you describe which browser you used? I'm trying on Firefox 81.0.1 on Win10 and cannot reproduce this.

**Comment by alfg** [comment] 2020-10-11 04:08
I'm also on Firefox 81.0.1/Win10, and I see the light theme flash while navigating between recipes.

**Comment by KevinLu** [comment] 2020-10-11 15:48
Ah yes, now I see it when I navigate between recipe pages.

**Comment by alfg** [comment] 2020-10-12 05:32
Fixed on #859

**Closed by alfg** 2020-10-12 05:32 UTC
Labels: bug, easy, good first issue, hacktoberfest
